ReadVerseWeb/Areas/Admin/Controllers/CompanyController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ReadVerse.DataAccess.Repository.IRepository;
using ReadVerse.Models;
using ReadVerse.Models.ViewModel;
using ReadVerse.Utility;

namespace ReadVerseWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]

    public class CompanyController : Controller
    {
            private readonly IUintOfWork _unitOFWork;
            public CompanyController(IUintOfWork unitOFWork)
            {
                _unitOFWork = unitOFWork;
            }
            public IActionResult Index()
            {
                var objCompanyList = _unitOFWork.Company.GetAll().ToList();
           
                return View(objCompanyList);
            }
            public IActionResult Upsert(int? id)
             {
            if (id == null || id == 0)
            {
                //create
                return View(new Company());

            }
            else
            {
                Company company=_unitOFWork.Company.Get(u=>u.Id==id);
                return View(company);
            }
        }
        [HttpPost]
        public IActionResult Upsert(Company company)
        {
            if (ModelState.IsValid)
            {

                if (company.Id == 0)
                {
                    _unitOFWork.Company.Add(company);
                }
                else
                {
                    _unitOFWork.Company.Update(company);
                }
                _unitOFWork.Save();
                TempData["success"] = "Product created successfully";
                return RedirectToAction("Index");
            }
            return View(company);

        }

        #region API CALLS for datatables.net
        [HttpGet]
        public IActionResult GetAll()
        {
            var objCompanyList = _unitOFWork.Company.GetAll().ToList();
                return Json(new {data=objCompanyList});
        }
        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var CompanyToRemvoed = _unitOFWork.Company.Get(u => u.Id == id);
            if(CompanyToRemvoed == null)
            {
                return Json(new {success=false,message="Error while deleting"});
            }
            
            _unitOFWork.Company.Remove(CompanyToRemvoed);
            _unitOFWork.Save();
            return Json(new { success = true, message = "Delete Successful" });
        }

        #endregion

    }
}

ReadVerseWeb/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ReadVerse.DataAccess.Repository.IRepository;
using ReadVerse.Models;
using ReadVerse.Models.ViewModel;
using ReadVerse.Utility;

namespace ReadVerseWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]

    public class ProductController : Controller
    {
            private readonly IUintOfWork _unitOFWork;
            private readonly IWebHostEnvironment _webHostEnvironment;
            public ProductController(IUintOfWork unitOFWork,IWebHostEnvironment webHostEnvironment)
            {
                _unitOFWork = unitOFWork;
                _webHostEnvironment=webHostEnvironment;
            }
            public IActionResult Index()
            {
                var objProductList = _unitOFWork.Product.GetAll(includeProperties:"Category").ToList();
           
                return View(objProductList);
            }
            public IActionResult Upsert(int? id)
        {
            IEnumerable<SelectListItem> CategoryList = _unitOFWork.Category.GetAll()
            .Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });
            //ViewBag.CategoryList = CategoryList;
            //ViewData["CategoryList"] = CategoryList;
            ProductVM productVM = new()
            {
                CategoryList = CategoryList,
                product = new Product()
            };
            if (id == null || id == 0)
            {
                return View(productVM);

            }
            else
            {
                productVM.product=_unitOFWork.Product.Get(u=>u.Id==id);
                return View(productVM);
            }
        }
            [HttpPost]
            public IActionResult Upsert(ProductVM productVM,IFormFile? file)
            {
               
                if (ModelState.IsValid)
                {
                string wwRootPath = _webHostEnvironment.WebRootPath;
                if (file != null)
                {
                    string filename=Guid.NewGuid().ToString()+Path.GetExtension(file.FileName);
                    string ProductPath=Path.Combine(wwRootPath,@"Images/Product");
                    if (!string.IsNullOrEmpty(productVM.product.ImageUrl))
                    {
                        var oldpath=Path.Combine(wwRootPath,productVM.product.ImageUrl.TrimStart('\\'));
                        if (System.IO.File.Exists(oldpath))
                        {
                            System.IO.File.Delete(oldpath); 
                        }
                    }
                    using (var filestream = new FileStream(Path.Combine(ProductPath, filename), FileMode.Create))
                    {
                        file.CopyTo(filestream);
                    }
                    productVM.product.ImageUrl = @"\Images\Product\" + filename;
                }
                if (productVM.product.Id == 0)
                {
                    _unitOFWork.Product.Add(productVM.product);
                }
                else
                    _unitOFWork.Product.Update(productVM.product);
                    _unitOFWork.Save();
                    TempData["success"] = "Product created successfully";
                    return RedirectToAction("Index");
                }
            else
            {

                productVM.CategoryList = _unitOFWork.Category.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                });
               
                return View(productVM);


            }
        }

        #region API CALLS for datatables.net
        [HttpGet]
        public IActionResult GetAll()
        {
            var objProductList = _unitOFWork.Product.GetAll(includeProperties: "Category").ToList();
                return Json(new {data=objProductList});
        }
        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            var ProductToRemvoed = _unitOFWork.Product.Get(u => u.Id == id);
            if(ProductToRemvoed == null)
            {
                return Json(new {success=false,message="Error while deleting"});
            }
            var oldpath = Path.Combine(_webHostEnvironment.WebRootPath, ProductToRemvoed.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(oldpath))
            {
                System.IO.File.Delete(oldpath);
            }
            _unitOFWork.Product.Remove(ProductToRemvoed);
            _unitOFWork.Save();
            return Json(new { success = true, message = "Delete Successful" });
        }

        #endregion

    }
}

ReadVerseWeb/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using ReadVerse.DataAccess.Data;
using ReadVerse.Models;


namespace ReadVerseWeb.Controllers
{
    public class CategoryController : Controller
    {
        private readonly AppDbContext _db;
        public CategoryController(AppDbContext db)
        {
            _db = db;   
        }
        public IActionResult Index()
        {
            var objCategoryList = _db.Categories.ToList();

            return View(objCategoryList);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Category obj)
        {
            if(obj.DisplayOrder.ToString()==obj.Name)
            {
                ModelState.AddModelError("name", "The DisplayOrder cannot exactly match the Name");
            }
            if (ModelState.IsValid)
            {
                _db.Categories.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Category created successfully";
                return RedirectToAction("Index");
            }
             return View();  
        }
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Category category=_db.Categories.Find(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }
        [HttpPost]
        public IActionResult Edit(Category obj)
        {
            
            if (ModelState.IsValid)
            {
                _db.Categories.Update(obj);
                _db.SaveChanges();
                TempData["success"] = "Category Updated successfully";
                return RedirectToAction("Index");
            }
            return View();
        }
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Category category = _db.Categories.Find(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }
        [HttpPost,ActionName("Delete")]
        public IActionResult DeletePOST(int? id)
        {
            Category obj = _db.Categories.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.Categories.Remove(obj);
            _db.SaveChanges();
            TempData["success"] = "Category deleted successfully";
           return RedirectToAction("Index");
        }
    }
}

ReadVerseWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ReadVerseWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />

    <link rel="stylesheet" href="~/ReadVerseWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/2.3.2/css/dataTables.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ReadVerse</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       
                        <li class="nav-item">
                            <a class="nav-link " asp-area="Customer" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Management
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                    </li>

                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                                    </li>

                                    <li><hr class="dropdown-divider"></li>

                                </ul>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link " asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                    <i class="bi bi-cart"></i>&nbsp;
                                </a>
                            </li>
                        }
                    </ul> 
                    <partial name="_LoginPartial"/>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-primary text-muted">
        <div class="container text-center">
            Made with<i class="bi bi-heart-fill"></i>Abdelaleam Ehab
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="//cdn.datatables.net/2.3.2/js/dataTables.min.js" asp-append-version="true"></script>
    <script src="https://cdn.tiny.cloud/1/27cht3rhnnp44kpg73c4v0zw83asnuoqep5kzs8si5hlsc40/tinymce/8/tinymce.min.js" referrerpolicy="origin" crossorigin="anonymous"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ReadVerseWeb/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
   <script type="text/javascript">
        toastr.success('@TempData["success"]');
   </script>
   
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}